# Generated by Django 4.2.11 on 2024-07-22 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
